---
cve: 2014-1858
title: CVE in numpy
description: >
    __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
cvss_v2: 2.1
references:
    - http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html
    - http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html
    - http://www.openwall.com/lists/oss-security/2014/02/08/3
    - http://www.securityfocus.com/bid/65441
    - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778
    - https://bugzilla.redhat.com/show_bug.cgi?id=1062009
    - https://exchange.xforce.ibmcloud.com/vulnerabilities/91318
    - https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst
    - https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15
    - https://github.com/numpy/numpy/pull/4262
affected:
    - name: numpy
      version:
        - "<=1.8.0"
      fixedin:
        - ">=1.8.1"
